### ISSUE TITLE
inlog problem

### ISSUE THREAD

**Issue by Tybald-the-cat** [Crisicus/maestro_mcz#17]
model stove: ST.SUITE/CLUB AIR 10 M2+

At the first entry field I get the message “unexpected error” when I have entered my login name and my password and press save after this.

**Comment by Robbe-B** [comment]
Hi, do you see anything in the logging ?

**Comment by Crisicus** [comment]
> model stove: ST.SUITE/CLUB AIR 10 M2+
> 
> At the first entry field I get the message “unexpected error” when I have entered my login name and my password and press save after this.

Can you update the integration to the latest release? (v0.2.2-beta)
I've added basic support for your stove while we're working on a better way to manage the models.

**Comment by Robbe-B** [comment]
I would say that it will be better to test with release => v0.2.3-beta.
Since this fixed a critical issue.

**Comment by Tybald-the-cat** [comment]
The installation was successful without any problems.
The heater can be switched on and off.
The temperature display is good.
But I can't tell if the heater is on or off.
it is always on  ¨uit-auto¨
I hope this is enough info for the next step.

Met vriendelijke groet,
Rob

Op wo 15 feb. 2023 om 10:19 schreef Robbe-B ***@***.***>:

**Comment by Crisicus** [comment]
On only shows when the stove is fully on, not warming up etc.

I'm in the process of adding a sensor that shows the actual current state.

The climate entity can only deal with on/off.

**Comment by Robbe-B** [comment]
Can we assume this login issue is fixed ?

**Comment by Tybald-the-cat** [comment]
Yes, But today the stove's Wi-Fi is down.
I don't know if it's due to too much communication or bad luck.
But I'll keep an eye on it.

Met vriendelijke groet,
Rob

Op do 16 feb. 2023 om 10:23 schreef Robbe-B ***@***.***>:
