### ISSUE TITLE
Wi-Fi from the stove cuts out

### ISSUE THREAD

**Issue by Tybald-the-cat** [Crisicus/maestro_mcz#20]
When I use the maestro _mcz from home assistant, the wifi of the stove crashes after about 7 to 8 hours.
The heater can only be reset by pulling the plug out of the socket.
If I use the original maestro app I don't have this problem.
I do not see any error messages in my log file in home assistant, with the exception that he has lost contact with the stove.
I've had this problem 4 times now.

**Comment by Robbe-B** [comment]
Well, that is a pitty ! This integration should not have any influence on the way your stove is connected over wifi. Do note that we only poll the MCZ cloud and not the stove directly. However, I believe you should end up have the same results when leaving your app open for more than 7-8 hours ? 
Since this feels like a hardware design issue to me (maybe some sort of 'buffer' getting full on the ESP board inside the stove ?)
I would suggest 2 possible fixes we can do here:

1. Make to polling time configurable in the MCZ integration as a option to see if this might be better with a higher polling time.

2. Make the MCZ integration start a new 'session' ever hour (to avoid getting a session related buffer growing too big)

**Comment by Tybald-the-cat** [comment]
In response to your email, I opened my tablet and the original app of the
stove and I'm going to see what happens.
If it happens again I'll let you know.

Op zo 19 feb. 2023 om 22:17 schreef Robbe-B ***@***.***>:

**Comment by Crisicus** [comment]
I've kept the polling to the same rate the app does for this reason.

However, the entire reason for me to reverse engineer the API was to see if I could prevent this issue, because it happened to my stove aswel.

I've turned off Bluetooth on the stove, and the issue seems to be better.

As @Robbe-B suggests, the stove runs on an ESP(32?), which is not that powerful and can run out of memory.

**Comment by Robbe-B** [comment]
All running the latest firmware for the internal boards, I assume ? (While checking I've noticed there was actually a firmware update for mine Club M2)
Check MCZ app => Adjustments/Settings => Firmware update

**Comment by Robbe-B** [comment]
@Crisicus, can you consistantly reproduce this on your stove aswell ? 
Could you check your firmware version aswell ?

**Comment by Crisicus** [comment]
Mine is running

- M2R.AIR.1
- DM2R.AIR.6.12.6

Which have been the "latest" for quite some time now.

**Comment by Tybald-the-cat** [comment]
Mine Is running

Type kaart M25AIR
Firmware Kaart M2S.15.8.Z221219A
Actieve database SA10

Firmware paneel DM2.AIR.8

For me is this the last one.

Op di 21 feb. 2023 om 12:40 schreef Crisicus ***@***.***>:

**Comment by Robbe-B** [comment]
Hmmm, for me this same one is available since 23/12/22, however, I didn't update the board firmware yet. 
Since I have no issues with the current firmware, I'm a bit hesitant to update, I'll potentially have the same issues afterwards.

**Comment by Robbe-B** [comment]
This made me also think, what about there 'wifi remote controls', they are also continuously polling the api, right ? 
![image](https://user-images.githubusercontent.com/103053873/220548586-62327b51-e82e-49c2-8e72-85bf63b354e7.png)

**Comment by Crisicus** [comment]
These models don't work with Maestro+ (M2) stoves. The old stoves used to send a local WiFi signal that implemented websockets. These probably connected to that.
There's some documentation on the ws "spec" floating around, but nothing we can use here.

**Comment by Tybald-the-cat** [comment]
If you google "mcz 4022002" you will get the right remote control.
I just can't find the technical details anywhere.

Op wo 22 feb. 2023 om 13:50 schreef Crisicus ***@***.***>:

**Comment by Tybald-the-cat** [comment]
Hello

Do you already have an idea when you are going to solve the problem with
the wifi of the stove getting stuck.

My idea is to disconnect from the stove once an hour and reconnect to the
stove after 15 seconds.

Op wo 22 feb 2023 om 17:36 schreef Rob ***@***.***>:

**Comment by Robbe-B** [comment]
Hi @Tybald-the-cat , 
At this moment, I'm not really sure what the problem with the stove is.
Since this home assistant integration is litterly doing the same as the android / IOS app would do.
What are the results of the test with keeping the app open for a long time ?

**Comment by Tybald-the-cat** [comment]
Hello Robbe-B

I performed the test with the mcz maestro+ app on a lenovo tablet for a
long time.
If I leave the app constant open after about 5 hours, the temperature
reading is not up to date.
If I try to start or stop the heater, I have to close the app and open it
again.
But the WiFi of the stove will remain intact.

I hope you can continue with this information.

Op wo 22 mrt 2023 om 07:26 schreef Robbe-B ***@***.***>:

**Comment by VaillantHassIo** [comment]
works a lot better with Bluetooth being disabled. ( Loop Air 8 M1+)

**Comment by Robbe-B** [comment]
Hi @Tybald-the-cat,
When you install v0.2.6-beta, you should now be able to configure the polling time of this integration (in the config options)
![image](https://user-images.githubusercontent.com/103053873/228175390-2a7e949a-7acd-44cf-846e-c835329d9486.png)
NOTE: Only values between 30-300 seconds are accepted as a valid input

Cheers !

**Comment by Tybald-the-cat** [comment]
Hello,
I have installed the install v0.2.6-beta.
Polling interval set to 60 sec.
After that, my wifi stopped dropping out.
This problem now appears to be resolved.

I have another wish is it possible to receive a temporary message that I
have turned on the heater.
It takes a long time before I can see that the stove is burning.

yours sincerely,
Rob

Op di 28 mrt 2023 om 10:25 schreef Robbe-B ***@***.***>:

**Comment by Robbe-B** [comment]
Hi @Tybald-the-cat,

Glad to hear your problem is resolved with a higher polling time.

For the other request you had, the climate se'sor turn already to 'Heat' when the stove is in 'start-up' mode, this issue is already solved in v0.2.10-beta.

**Comment by VaillantHassIo** [comment]
> > @Crisicus, Any idea on how we want to move forward with this ? Since I can't reproduce this issue with my stove / firmware, could you take a look at this ?
> 
> I don't think there's any way to move forward other than to have to poll rate be something configurable with an input or slider. As @VaillantHassIo states, my stove has been working fine (1 "blackout" the past 1,5 month) since turning BLE off physically on the stove.

Can you remind me on how to disable BT when Wifi is enabled? Presing the button for 5 Sec always enters the Wifi Configuration
