### ISSUE TITLE
Login issue - MCZ Halo Air Up!

### ISSUE THREAD

**Issue by k3ruakk** [Crisicus/maestro_mcz#22]
Stove: HALO AIR 8 UP! M1

When I try to log in, I also get a "unexpected error” message.
I'm supposed to use S/N and MAC as username/password, right?

**Comment by Robbe-B** [comment]
Hi @k3ruakk, I believe this integration is not suitable for your stove.
It will only work for those using the black mobile app. Called 'Maestro MCZ'.
<img src="https://github.com/Crisicus/maestro_mcz/blob/main/docs/app_icon.png" width="64" height="64">
