### ISSUE TITLE
Add support for MCZ Loop Air 8 M1+

### ISSUE THREAD

**Issue by VaillantHassIo** [Crisicus/maestro_mcz#23]
As discussed open a Feature Request to Add support for MCZ Loop Air 8 M1+

Currently it only has 1 Device incl. 1 Climate Entity.

Unfortunately there is no option to Download the Diagnostics File. Below an excerpt from Development Tools

`hvac_modes:
  - 'off'
  - heat
min_temp: 5
max_temp: 40
fan_modes:
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
preset_modes:
  - manual
  - auto
  - overnight
  - comfort
  - turbo
swing_modes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
current_temperature: 21.8
temperature: 16
fan_mode: None
preset_mode: manual
swing_mode: '0'
icon: mdi:stove
friendly_name: Pelletofen
supported_features: 57`

**Comment by Robbe-B** [comment]
In order to download the diagnostics file you should run v0.2.4-beta  (released  2 days ago)

**Comment by VaillantHassIo** [comment]
[config_entry-maestro_mcz-466d8e4de749e610e22c8bce7783edad.json.txt](https://github.com/Crisicus/maestro_mcz/files/11062972/config_entry-maestro_mcz-466d8e4de749e610e22c8bce7783edad.json.txt)

Please remove the attachement once downloaded

**Comment by Robbe-B** [comment]
Thanks & Done ! I'll have a look on Monday !

**Comment by VaillantHassIo** [comment]
Thanks for the quick implemenation. Below are the screenshots. not sure what the FAN entitry is being used for (  i will test before i switch the oven off )

![grafik](https://user-images.githubusercontent.com/87522613/228143823-5808e37b-2fe3-44e5-bf84-14ae3af93ab7.png)

One more thing. The oven officially supports only 5 FAN Level but has 6 in the DropDown List

![grafik](https://user-images.githubusercontent.com/87522613/228144052-99b267c2-6d83-470d-801b-64e6ed141d0d.png)

Cheers

**Comment by VaillantHassIo** [comment]
Fan Speed 6 will basically set the FAN Speed to Automatic. I will open a new issue for tracking purposes

**Comment by Robbe-B** [comment]
We are aware of this, internally this is mapped.
0= silent
6=auto
Should be fixed once we start using the dynamic configs

**Comment by VaillantHassIo** [comment]
And i guess the FAN entity On/off is a HA preset. Its states failure calling service. 

![grafik](https://user-images.githubusercontent.com/87522613/228147282-989603c5-f437-4a6a-b598-eb0fb900bc3e.png)

**Comment by Robbe-B** [comment]
I'm also aware of this 👍 .
At the moment this is a bit messy.
When I find the time, I'll fix all these small inconveniences.

**Comment by VaillantHassIo** [comment]
Appreciate your work. thanks again

**Comment by VaillantHassIo** [comment]
The Loop Air Supports 5 Fan levels and 2 Modus ( Automatic & Silennt)

new issue created: https://github.com/Crisicus/maestro_mcz/issues/27
