### ISSUE TITLE
FAN entity ( switch ) - can't toggle on/off - failure calling service fan/turn_off fan/turn_on

### ISSUE THREAD

**Issue by VaillantHassIo** [Crisicus/maestro_mcz#27]
Seem the Fan entity is not meant to act as a switch as you cant switch off/on the FAN itself just regulate/configure the level or modus

![grafik](https://user-images.githubusercontent.com/87522613/228188260-6e2b7e58-8808-4b40-8bb4-15e0fc1d1e8e.png)

HA Source: https://www.home-assistant.io/integrations/fan/#service-fanturn_on

**Comment by Robbe-B** [comment]
@VaillantHassIo,
This issue should be resolved by installing v0.2.10-beta.
Cheers !
