### ISSUE TITLE
Setup erneut versuchen: 'index_vel_v2' // Try setup again: 'index_vel_v2'

### ISSUE THREAD

**Issue by ftwmoe** [Crisicus/maestro_mcz#35]
Hi,

I've an EGO Hydromatic 12 M2+ (Mainboard Type: M2.HYD, Firmware 5.5, Database active: HYD-M_12) which doesn't work with your integration.

![Screenshot_20230419_101511](https://user-images.githubusercontent.com/8835779/233012658-ac05cafe-df46-4a18-92c0-5570e5f35ce0.jpg)

Unfortunately (as you assumed), there is no "diagnostic" option, as the integration fails.
As requested in HA community I'd like to kindly ask you, to build a model specific config for that type of stove.

Thanks a lot!

Br, Sam

PS.: Please tell me, how to support you guys - I want to show my gratitude!

**Comment by Robbe-B** [comment]
Hi @ftwmoe, I'll look into fixing this problem.
I also believe you are the first to use this integration with a hydro type of stove. 
I'm curious if there are many differences in controlling these compared to a regular stove ? 
Can you maybe show a screenshot of your MCZ app ? (This is out of curiosity)
After the fix it could also be interesting for us to look in to your diagnostics file.

NOTE: I'm not in this for the support, but here you go if you really want to => https://www.buymeacoffee.com/RBprojects
Not sure about @Crisicus if he has an account to support him as well.

**Comment by ftwmoe** [comment]
Good morning @Robbe-B, thanks in advance!

Here you are (first two are from advanced menu):
![Screenshot_20230425_081723](https://user-images.githubusercontent.com/8835779/234190725-8e358b7a-9695-4227-9efb-c2d0c26f743a.jpg)
![Screenshot_20230425_081735](https://user-images.githubusercontent.com/8835779/234190732-8e0d2d6e-c9dc-4458-b1fd-929077424151.jpg)
![Screenshot_20230425_081601](https://user-images.githubusercontent.com/8835779/234190733-0377c7da-de14-4ac6-aabe-cebd4d8b1b62.jpg)

Br, Sam



> Hi @ftwmoe, I'll look into fixing this problem. I also believe you are the first to use this integration with a hydro type of stove. I'm curious if there are many differences in controlling these compared to a regular stove ? Can you maybe show a screenshot of your MCZ app ? (This is out of curiosity) After the fix it could also be interesting for us to look in to your diagnostics file.
> 
> NOTE: I'm not in this for the support, but here you go if you really want to => https://www.buymeacoffee.com/RBprojects Not sure about @Crisicus if he has an account to support him as well.

**Comment by Robbe-B** [comment]
In above linked PR, a lot has been changed:
- We moved away from the manual config entry for each stove model & has been replaced with an automatic config discovery mechanism
- We don't crash anymore when a value in not found in a response (apparently this can be different for various stove models)
- We've added the unknown fields from a response message in the diagnostics file (we potentially need this in the future in order to move forward, supporting more stove models)
- Lot's of other small improvements under the hood of this integration

This is worth a shot for your stove model, I don't think everything will work flawless from the beginning, but once we can get your diagnostics file, we'll see where we get 😄 

Kind Regards, 

Robbe-B

**Comment by ftwmoe** [comment]
Hi @Robbe-B,

thank you so much! Integrated now successfully. 
The basics are working now 👍 

First issue I've found is: Fehler beim Aufrufen des Diensts climate/set_temperature. 'MczClimateEntity' object has no attribute 'supported_fan'

My diagnostics file attached :)

Kind regards, Sam

[config_entry-maestro_mcz-d63a342ac4e9e37e1b12493bc5221b29.json.txt](https://github.com/Crisicus/maestro_mcz/files/11326563/config_entry-maestro_mcz-d63a342ac4e9e37e1b12493bc5221b29.json.txt)

**Comment by Robbe-B** [comment]
Thanks for sharing the diagnostics ! 
You mind sharing a screenshot of how the integrations now looks for you ?

**Comment by ftwmoe** [comment]
Here you go 

![Screenshot 2023-04-25 225608](https://user-images.githubusercontent.com/8835779/234401823-7f192c47-98bb-4cd9-a740-aaab936c1da3.png)

**Comment by RickType** [comment]
Hi,

I have a very similar oven.
Modell: ST.MUSA Hydromatic 18 M2+
Platine: M25.HYD
Firmware: 5.5
Data Base HYD-M_18

Unfortunatley I get the same error message: Retrying setup: 'index_vel_v2'

Are you able to help me as well?

Thanks a lot
Patrick

[home-assistant_maestro_mcz_2023-04-28T20-06-16.957Z.log](https://github.com/Crisicus/maestro_mcz/files/11356968/home-assistant_maestro_mcz_2023-04-28T20-06-16.957Z.log)

**Comment by RickType** [comment]
Hi,

I have a very similar oven.
Modell: ST.MUSA Hydromatic 18 M2+
Platine: M25.HYD
Firmware: 5.5
Data Base HYD-M_18

Unfortunatley I get the same error message: Retrying setup: 'index_vel_v2'

Are you able to help me as well?

Thanks a lot
Patrick

[home-assistant_maestro_mcz_2023-04-28T20-06-16.957Z.log](https://github.com/Crisicus/maestro_mcz/files/11356968/home-assistant_maestro_mcz_2023-04-28T20-06-16.957Z.log)
[home-assistant_maestro_mcz_2023-04-28T20-06-16.957Z.log](https://github.com/Crisicus/maestro_mcz/files/11356994/home-assistant_maestro_mcz_2023-04-28T20-06-16.957Z.log)

**Comment by Robbe-B** [comment]
@RickType, I'm currently improving the changes I made to dynamically support the different stove models. 
Soon, when it's good enough.
I'll release this for the first time to the public 🤞 
Do note that the above linked PR is already usable for you. 
I would probably need your diagnostics file as well to see on what we can further improve.
Kind regards

**Comment by RickType** [comment]
Thanks a lot! I need to figur out how to download the PR. I saw your changes but I don't know how to implement it.
Until now there was no need to implement HACS, therefore I need to get familar with it.
The diagnostic file is only availabe when the integration successfully loaded? Or were can I find it?

**Comment by Robbe-B** [comment]
@ftwmoe , PR is updated normally this exception should not happen anymore now.
Kind regards

**Comment by Robbe-B** [comment]
@ftwmoe, @RickType , 
Try installing[ v0.3.0-beta](https://github.com/Crisicus/maestro_mcz/tree/v0.3.0-beta).
Could you both provide me a diagnostics file after doing so ?
That would be great ! 
I'm looking into adding more features for the hydro models in the near future !

**Comment by RickType** [comment]
Manny tanks Robbe. Awesome work! Really appreciate your effort. Long time ago I studied computer engineering and I'm also willing to contribute. But I need some time to get familiar with it. Attached a screenshot of the Device in HASS and the Diagnostic file.
![MCZDashboard](https://user-images.githubusercontent.com/132100934/235342205-8cb5315b-89bf-4542-8828-16f8a1762360.png)
[config_entry-maestro_mcz-96588d176a8338c6fd96afcfc30965b1.json.txt](https://github.com/Crisicus/maestro_mcz/files/11360825/config_entry-maestro_mcz-96588d176a8338c6fd96afcfc30965b1.json.txt)

**Comment by Robbe-B** [comment]
@RickType, thanks for sharing your screenshot. 
However, I see there are still many things wrong with it.
I see many fields inside the status message are just blank for your stove model 😞.
Even the fields that should display the firmware versions ....
Don't you see any exceptions or errors in the logging related to this integration ?

**Comment by Robbe-B** [comment]
@RickType, 
Would it be possible to provide me with the same screenshots as @ftwmoe did ?  (advanced screens also inside the MCZ app) 
And provide me the diagnostics file from this integration at the very same moment of taking the MCZ app screenshots ? 
By doing so it's easier for me to make sense of the different fields related to the hydro models.

I already have a commit ready for these fields of hydro stoves, but I want to make sure this is the same for your model.
Thanks !

**Comment by RickType** [comment]
Sure, I'm currently on a business trip but will be back tomorrow...

**Comment by RickType** [comment]
Hi Robbe,

here you are. Sorry for the late response. Was fighting with my Modbus Config for my Headpump.

Cheers
Patrick

![Advanced_TempSettings1](https://github.com/Crisicus/maestro_mcz/assets/132100934/f59f4add-7464-43c0-9b45-02709d0f1d55)
![Advanced_TempSettings2](https://github.com/Crisicus/maestro_mcz/assets/132100934/4e480e65-9c6e-4fbc-870f-f19fdf50fad3)
![AdvancedSettingsMain](https://github.com/Crisicus/maestro_mcz/assets/132100934/313286e7-aff9-4698-994b-af9b5510b890)
![Chrono](https://github.com/Crisicus/maestro_mcz/assets/132100934/476a3b17-d0f0-4ecb-b634-04fcb4f9b6df)
![Counter](https://github.com/Crisicus/maestro_mcz/assets/132100934/7dd856f1-ca8d-42ab-8029-49b991761286)
![Main_BoilerTemp](https://github.com/Crisicus/maestro_mcz/assets/132100934/43f2761c-0440-4ee5-ac9c-a78454d06027)
![Main_BufferTemp](https://github.com/Crisicus/maestro_mcz/assets/132100934/e835d740-6118-4c35-ba7e-d22534812dcb)
![PelletSensorOnOff](https://github.com/Crisicus/maestro_mcz/assets/132100934/29547d92-3c81-47b3-9f44-5d3297bf52c9)
![RealtimeData1](https://github.com/Crisicus/maestro_mcz/assets/132100934/d34a907f-4586-4e01-b9e5-d944112191b8)
![RealTimeData2](https://github.com/Crisicus/maestro_mcz/assets/132100934/61fd0d88-0574-45ca-8cd7-6ca65b034a37)
![RealTimeData3](https://github.com/Crisicus/maestro_mcz/assets/132100934/fe9a5095-b716-4962-bb7e-2bb38c777bc5)
![Rezepte](https://github.com/Crisicus/maestro_mcz/assets/132100934/ed4eae79-1098-4f91-8dc3-51aaf12f35b2)
![SetModus](https://github.com/Crisicus/maestro_mcz/assets/132100934/3d84e8a9-9bc2-410b-ae83-70f4439b27ab)
![Settings](https://github.com/Crisicus/maestro_mcz/assets/132100934/bc72caaf-e4ba-4f28-9e37-e86ef01d5f82)
[json.zip](https://github.com/Crisicus/maestro_mcz/files/11484931/json.zip)

**Comment by Robbe-B** [comment]
@RickType,
Thanks for your efforts in taking these the screenshots.
As soon as I have the time, I'll look into supporting the most obviouse features of your hydromodel.
Kind Regards,
Robbe B

**Comment by RickType** [comment]
Thanks Robbe.
Have unseen the attached zip with the json files?
My wishlist would comprise of:
- Display Buffer temperature —> Please not that config mode 6 is that you will heat a buffer with PTC sensor connected to the stove.
- Set water temperature for the boiler incl. hysteresis 
- set water temperature of the buffer

Thanks again for effort.

Patrick
