### ISSUE TITLE
wifi disconnected

### ISSUE THREAD

**Issue by Leon3310** [Crisicus/maestro_mcz#37]
Hi,

I tried to use the integration several times. Everything is fine but after a few hours, the wifi logo flashes and the stove is unavailable on home assistant. It is no longer accessible on mobile phones either.

I set the "pooling interval" variable to 120.

To get the wifi back, I have to turn off the power.

Do you have the same problem as me? Is there anything special to do?

**Comment by Robbe-B** [comment]
Hi, I'm sorry to hear you have this problem. 
We are already aware of simular problems.
Does the higher polling interval help mitigate the issue?

**Comment by Robbe-B** [comment]
@Leon3310,
Would it be possible to add your diagnostics file as well ? 
With that I can follow up on the stove firmware versions with this problem.
Thanks !

**Comment by Leon3310** [comment]
[config_entry-maestro_mcz-6f1c0247608bfa5e0d7916195467a787.json.txt](https://github.com/Crisicus/maestro_mcz/files/11336869/config_entry-maestro_mcz-6f1c0247608bfa5e0d7916195467a787.json.txt)

**Comment by Leon3310** [comment]
Thank you, I haven't had any more bugs since and everything seems to be working fine now

**Comment by Robbe-B** [comment]
Thanks for the update !

**Comment by VaillantHassIo** [comment]
what was the solution and how to disable BT when Wifi is enabled ( press 5 sec always brings me to Wifi Settings )
